<?php


namespace model;


use model\mappers\Mapper;
use ReflectionException;

final class ResultSet {
    /**
     * The data in an array
     * @var array
     */
    private $data;

    /**
     * ResultSet constructor.
     * @param array $data
     */
    public function __construct(array $data) {
        $this->data = $data;

        // Get rid of numeric keys generated by PDO or whatever
        foreach ($this->data as $key => $row) {
            foreach ($row as $k => $v) {
                if (is_numeric($k)) unset($this->data[$key][$k]);
            }
        }
    }

    /**
     * @param Mapper $mapper
     * @return array
     */
    public function map(Mapper $mapper) {
        return $mapper->map($this);
    }

    /**
     * @return array
     */
    public function getRows() {
        return $this->data;
    }
}