-- noinspection SqlDialectInspectionForFile

-- noinspection SqlNoDataSourceInspectionForFile

-- These definitions were auto-generated by DataGrip taken the changes we finally made to Maxime's work

-- auto-generated definition
CREATE TABLE message_fragments
(
    id            int                                 NOT NULL
        PRIMARY KEY,
    message_id    int                                 NOT NULL,
    creator_id    int                                 NOT NULL,
    content       varchar(255)                        NOT NULL,
    creation_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT message_fragments_messages_id_fk
        FOREIGN KEY (message_id) REFERENCES messages (id),
    CONSTRAINT message_fragments_users_id_fk
        FOREIGN KEY (creator_id) REFERENCES users (id)
);

-- auto-generated definition
CREATE TABLE messages
(
    id            int                                 NOT NULL
        PRIMARY KEY,
    thread_id     int                                 NOT NULL,
    creation_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT messages_threads_id_fk
        FOREIGN KEY (thread_id) REFERENCES threads (id)
);

-- auto-generated definition
CREATE TABLE password_resets
(
    user_id       int                                 NOT NULL
        PRIMARY KEY,
    token         char(32)                            NOT NULL,
    creation_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT password_resets_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE threads
(
    id            int                                  NOT NULL
        PRIMARY KEY,
    creator_id    int                                  NOT NULL,
    opened        tinyint(1) DEFAULT 1                 NOT NULL,
    creation_date timestamp  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT threads_users_id_fk
        FOREIGN KEY (creator_id) REFERENCES users (id)
);

-- auto-generated definition
CREATE TABLE users
(
    id       int                  NOT NULL
        PRIMARY KEY,
    username varchar(255)         NOT NULL,
    email    varchar(30)          NOT NULL,
    password varchar(255)         NOT NULL,
    admin    tinyint(1) DEFAULT 0 NOT NULL
);

